
package com.dell.rabbit.javaeesample.internal.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWsService", targetNamespace = "http://service.javaeesample.rabbit.dell.com/", wsdlLocation = "file:/D:/workspace/javaee_samples/rabbit-javaeesample/rabbit_sample/src/main/webapp/META-INF/wsdl/HelloWs.wsdl")
public class HelloWsService
    extends Service
{

    private final static URL HELLOWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(HelloWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = HelloWsService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/workspace/javaee_samples/rabbit-javaeesample/rabbit_sample/src/main/webapp/META-INF/wsdl/HelloWs.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/workspace/javaee_samples/rabbit-javaeesample/rabbit_sample/src/main/webapp/META-INF/wsdl/HelloWs.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWSSERVICE_WSDL_LOCATION = url;
    }

    public HelloWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWsService() {
        super(HELLOWSSERVICE_WSDL_LOCATION, new QName("http://service.javaeesample.rabbit.dell.com/", "HelloWsService"));
    }

    /**
     * 
     * @return
     *     returns HelloWs
     */
    @WebEndpoint(name = "HelloWsPort")
    public HelloWs getHelloWsPort() {
        return super.getPort(new QName("http://service.javaeesample.rabbit.dell.com/", "HelloWsPort"), HelloWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWs
     */
    @WebEndpoint(name = "HelloWsPort")
    public HelloWs getHelloWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.javaeesample.rabbit.dell.com/", "HelloWsPort"), HelloWs.class, features);
    }

}
